### ISSUE TITLE
UEFI boot loader support

### ISSUE THREAD

**Issue by Ratler** [lunar-linux/lunar-iso#11]
We need to create a couple of UEFI boot loader modules and make them available in the installer.

gummiboot, elilo etc

**Comment by Ratler** [comment]
- [ ] Remove gummiboot, it's already deprecated and merged into systemd
- [ ] Add EFI support to our grub2 module

**Comment by mwgrient** [comment]
Would love to see this happen, so I can use lunar-linux on my intel iMac!

**Comment by Florin65** [comment]
we can consider refind too.
http://www.rodsbooks.com/refind/linux.html
http://www.rodsbooks.com/refind/index.html

**Comment by mwgrient** [comment]
Yes! Although refind refuses at this time to boot the iso image on a usb pen drive (created with dd). I have a iMac version 17,1 (late 2015). Refind should boot legacy linux, but not the lunar-linux (stable, or testing4) iso.

**Comment by dagbrown** [comment]
Here we are in the year of our lord 2022, and EFI support still isn't complete.

When you make /boot a VFAT file system to use as an EFI boot, the installer doesn't create the EFI directory to put the EFI stuff into.

**Comment by dagbrown** [comment]
And here we are a couple of years after that, and it would seem that EFI boot support is finally complete.
