### ISSUE TITLE
pepperflash issue

### ISSUE THREAD

**Issue by mwgrient** [lunar-linux/lunar-iso#18]
For the maintainer of pepperflash I have the following issue:

root@tulp ~ # lin pepperflash 
Checking dependencies for pepperflash 
Building pepperflash version 16.0.0.235
! sha256sum check failed for google-chrome-stable_current_amd64.deb
You should remove google-chrome-stable_current_amd64.deb !
pepperflash: Remove "/var/spool/lunar/google-chrome-stable_current_amd64.deb" ?  [y] 

To bypass it I use the -w flag. So it does not check for the sha256sum.

**Comment by Ratler** [comment]
Closing this issue. A new version of pepperflash is available in the moonbase.
