### ISSUE TITLE
Gcc iso 1.7.1 

### ISSUE THREAD

**Issue by mwgrient** [lunar-linux/lunar-iso#21]
Hello
What is the reason for using gcc 5.1 on the testing3 iso image of lunar 1.7.1? If i do a lin moonbase, gcc 4.9.2 is replacing the gcc version of the iso image...
Marco

**Comment by Ratler** [comment]
As name in the ISO suggests it's for testing purposes. In this case we test that the next major version of gcc can build all modules in moonbase/core. I suggest that you do "lunar hold gcc", but of course you can downgrade gcc if you prefer. Eventually it will be bumped in moonbase.
