### ISSUE TITLE
moonbase is missing on testing4 iso

### ISSUE THREAD

**Issue by mwgrient** [lunar-linux/lunar-iso#28]
There is no moonbase installed on the iso, perhaps with a reason? 

Update: I mean when I have installed Lunar-Linux  with this iso, there is no moonbase present.

**Comment by v4hn** [comment]
On Sun, Jan 15, 2017 at 07:48:30AM -0800, mwgrient wrote:
> There is no moonbase installed on the iso, perhaps with a reason? 

Yes, it would be obsolete short after the generation of the iso.

The first thing `man lfirsttime` tells you to do, after setting up your network, is to run `lin moonbase`.
