### ISSUE TITLE
No login prompt in new installations

### ISSUE THREAD

**Issue by esselfe** [lunar-linux/lunar-iso#59]
When the system is installed and booted into, systemd stops at "[ OK  ]  Reached Target Graphical Interface." and only provide login prompt for tty 2-6 and can be accessed by typing alt+F2. This is a very confusing situation for new users.

The required steps to resolve this is to run:
`systemctl enable getty@tty1.service`
`systemctl start getty@tty1.service`

**Comment by dagbrown** [comment]
Fixed with PR#62
