### ISSUE TITLE
Creating xfs filesystems fails at install time

### ISSUE THREAD

**Issue by dagbrown** [lunar-linux/lunar-iso#67]
It prints out an error that it can't load `/usr/lib/libinih.so.0` and immediately exits without creating a filesystem.

The `inih` package is on /var/cache/lunar on the iso, but it's not installed on the live filesystem that the installer runs from.

**Comment by Ratler** [comment]
Fixed in https://github.com/lunar-linux/lunar-iso/commit/6ce65fde8af0245f89767318ba121fc1a286daed
